language: ruby
cache:
  bundler: true
  directories:
    - bower_components
sudo: false
rvm:
  - 2.3.0
before_script:
  - npm install bower
  - bundle exec rake compile
  - bundle exec rake serve > /dev/null 2>&1 &
  - export PID=$!
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
script:
  - bundle exec rake spec
after_failure:
  - bundle exec rake upload
after_script:
  - kill -2 $PID
  - sleep 2
env:
  matrix:
    - "BROWSER=firefox TOLERANCE=0.000001"
    - "BROWSER=firefox TOLERANCE=0.000000"
matrix:
  fast_finish: true
  allow_failures:
    - env: BROWSER=firefox TOLERANCE=0.000000
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1184f6f283ba9823f662
    on_success: change
    on_failure: always
    on_start: never
